In [9]:
import numpy as np
import pandas as pd
from sklearn import linear_model

In [66]:
n=int(input('enter the no of variables:'))
# l=[]
# for i in range(n):
#     l.append(list(map(int,input().split())))
# print(l)

enter the no of variables:3


In [67]:
df=pd.DataFrame()
for i in range(n):
    df[input('enter the variable name:')]=list(map(int,input().split()))

100 110 105 94 95 99 104 108 105 98 105 110
enter the variable name:sales
9 8 7 14 12 10 7 4 6 5 7 6 
enter the variable name:precentage_of_absentism
62 58 64 60 63 57 55 56 59 61 57 60
enter the variable name:breakdown


In [81]:
df

sales  precentage_of_absentism  breakdown
0     100                        9         62
1     110                        8         58
2     105                        7         64
3      94                       14         60
4      95                       12         63
5      99                       10         57
6     104                        7         55
7     108                        4         56
8     105                        6         59
9      98                        5         61
10    105                        7         57
11    110                        6         60

# BUILT IN FUN

In [72]:
m=df.iloc[:,1:]

In [73]:
m

precentage_of_absentism  breakdown
0                         9         62
1                         8         58
2                         7         64
3                        14         60
4                        12         63
5                        10         57
6                         7         55
7                         4         56
8                         6         59
9                         5         61
10                        7         57
11                        6         60

In [79]:
reg=linear_model.LinearRegression()
reg.fit(m,df['sales'])

LinearRegression()

In [80]:
reg.coef_

array([-1.24850346, -0.35100837])

# MANUAL

In [101]:
## for insertion of 1's column
length=len(df['sales'])
X=np.ones((length,1))
X=np.hstack((X,df.iloc[:,1:]))

In [102]:
X

array([[ 1.,  9., 62.],
       [ 1.,  8., 58.],
       [ 1.,  7., 64.],
       [ 1., 14., 60.],
       [ 1., 12., 63.],
       [ 1., 10., 57.],
       [ 1.,  7., 55.],
       [ 1.,  4., 56.],
       [ 1.,  6., 59.],
       [ 1.,  5., 61.],
       [ 1.,  7., 57.],
       [ 1.,  6., 60.]])

In [120]:
y=np.array(df['sales']).reshape(12,1)

#y.
#np.shape(y)
y=np.matrix(y)
print(y)

[[100]
 [110]
 [105]
 [ 94]
 [ 95]
 [ 99]
 [104]
 [108]
 [105]
 [ 98]
 [105]
 [110]]


In [124]:
## transpose of matrix

Xtrans=[[X[i][j] for i in range(len(X))] for j in range(len(X[0]))]
#Xtrans




In [132]:
res1= (Xtrans*y)

##     inverse of the matrix

res =np.linalg.inv(Xtrans@X)@res1

In [134]:
print('THE COEFFICIENT MATRIX IS:',res)

THE COEFFICIENT MATRIX IS: [[133.46048243]
 [ -1.24850346]
 [ -0.35100837]]


# GOODNESS OF FIT

## 1.COEFFICIENT OF DETERMINATION

In [136]:
ylist=float(res[0])+float(res[1])*df['precentage_of_absentism']+float(res[2])*df['breakdown']

In [137]:
ylist

0     100.461432
1     103.113969
2     102.256422
3      94.920932
4      96.364914
5     100.967971
6     105.415498
7     108.810000
8     105.259968
9     105.806454
10    104.713481
11    104.908959
dtype: float64

In [151]:
ydf=pd.DataFrame({'y':df['sales']
                 ,'y^':list(ylist)})
ydf['$']=(ydf['y']-ydf['y^'])**2

In [159]:
SSe=sum(ydf['$'])
#SSe

from statistics import mean
avg_of_sales=mean(df['sales'])
SST=sum((df['sales']-avg_of_sales)**2)
#SST

SSr=SST-SSe

R2=SSr/SST
if R2>0.90:
    print('It fits in the model')
else:
    print('It won\'t fit in the model')

it won't fit in the model


## 2.ANOVA CLASSIFICATION

In [165]:
msr=SSr/(n-1)
mse=SSe/(length-n)
los=float(input('enter the level of significance:'))
Fcal=msr/mse
from scipy import stats
Ftab=stats.f.ppf(1-los,n-1,length-n)
if Fcal<=Ftab:
    print('Not A Good Fit')
else:
    print('Good Fit')

enter the level of significance:0.05
Good Fit
