In [14]:
import numpy as np
 

In [12]:
print(numpy.__version__ , numpy.show_config())

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
1.20.3 None


In [15]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [18]:
l=[1,2,3,4,5,6,7]
a=np.array(l)

if 0 in a:
    print('present')
else:
    print('not present')
a

not present


array([1, 2, 3, 4, 5, 6, 7])

In [31]:
# 4

a=np.ones(10)
b=np.zeros(10)
c=np.array([5]*10)
print(a,b,c)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] [5 5 5 5 5 5 5 5 5 5]


In [61]:

l=np.arange(30,70,2)

l

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68])

In [62]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [72]:
l=np.arange(21)

l[(l>9)&(l<15)]*=(-1)

print(l)

[  0   1   2   3   4   5   6   7   8   9 -10 -11 -12 -13 -14  15  16  17
  18  19  20]


In [74]:
l.shape

(21,)

In [86]:
a=np.zeros(100).reshape(10,10)
# print(a)

a[0]=1

a[0:,0]=1

a[0:,-1]=1

a[-1]=1

a


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [102]:
#same array as above cell

a[2][3]=100
print(a)
print(sum(a[:,i] for i in range(10)))
print(sum(a))
print(np.sum(a))

[[  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   0.   0.   0.   0.   0.   0.   0.   0.   1.]
 [  1.   0.   0. 100.   0.   0.   0.   0.   0.   1.]
 [  1.   0.   0.   0.   0.   0.   0.   0.   0.   1.]
 [  1.   0.   0.   0.   0.   0.   0.   0.   0.   1.]
 [  1.   0.   0.   0.   0.   0.   0.   0.   0.   1.]
 [  1.   0.   0.   0.   0.   0.   0.   0.   0.   1.]
 [  1.   0.   0.   0.   0.   0.   0.   0.   0.   1.]
 [  1.   0.   0.   0.   0.   0.   0.   0.   0.   1.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]]
[ 10.   2. 102.   2.   2.   2.   2.   2.   2.  10.]
[ 10.   2.   2. 102.   2.   2.   2.   2.   2.  10.]
136.0


In [103]:
l=[1,2,3,4,5]
a=np.array(l)
b=list(a)
l==b

True

In [142]:
from  random import random as rand

l=np.array([rand()*10 for i in range(27)],dtype=int).reshape(3,3,3)
print(l)

[[[0 2 6]
  [6 6 0]
  [0 3 3]]

 [[6 6 9]
  [1 1 4]
  [8 3 6]]

 [[1 5 6]
  [0 9 9]
  [6 3 9]]]


In [141]:
# l=np.zeros((5,5))

l=np.diag([1,2,3,4,5])

l
# l.diag([i for i in range(5)])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [153]:
l=np.array([rand()*10 for i in range(9)],dtype=int).reshape(3,3)

print(l)

print(l[l>4],l[l<4])

[[3 6 9]
 [8 0 9]
 [2 6 5]]
[6 9 8 9 6 5] [3 0 2]


In [159]:
l1=np.array([rand()*10 for i in range(9)],dtype=int).reshape(3,3)

print(l1)

l2=np.array([rand()*10 for i in range(9)],dtype=int).reshape(3,3)

print(l2)

np.intersect1d(l1,l2)

[[5 2 7]
 [8 9 2]
 [4 5 8]]
[[9 8 2]
 [2 8 8]
 [8 6 3]]


array([2, 8, 9])

# Lab Cycle 2

In [4]:
import pandas as pd
import numpy as np

In [2]:
fil=pd.read_csv('Z:\\DA\\winequality-red.csv')
fil

fixed acidity;"volatile acidity";"citric acid";"residual sugar";"chlorides";"free sulfur dioxide";"total sulfur dioxide";"density";"pH";"sulphates";"alcohol";"quality"
0      7.4;0.7;0;1.9;0.076;11;34;0.9978;3.51;0.56;9.4;5                                                                                                                     
1      7.8;0.88;0;2.6;0.098;25;67;0.9968;3.2;0.68;9.8;5                                                                                                                     
2     7.8;0.76;0.04;2.3;0.092;15;54;0.997;3.26;0.65;...                                                                                                                     
3     11.2;0.28;0.56;1.9;0.075;17;60;0.998;3.16;0.58...                                                                                                                     
4      7.4;0.7;0;1.9;0.076;11;34;0.9978;3.51;0.56;9.4;5                                                                                                                     
...                                                 ...                                                                                                                     
1594  6.2;0.6;0.08;2;0.09;32;44;0.9949;3.45;0.58;10.5;5                                                                                                                     
1595  5.9;0.55;0.1;2.2;0.062;39;51;0.99512;3.52;0.76...                                                                                                                     
1596  6.3;0.51;0.13;2.3;0.076;29;40;0.99574;3.42;0.7...                                                                                                                     
1597  5.9;0.645;0.12;2;0.075;32;44;0.99547;3.57;0.71...                                                                                                                     
1598  6;0.31;0.47;3.6;0.067;18;42;0.99549;3.39;0.66;...                                                                                                                     

[1599 rows x 1 columns]

In [91]:
wines=np.genfromtxt('Z:\\DA\\winequality-red.csv',dtype=float,delimiter=';',skip_header=1)

In [14]:
wines.shape

(1599, 12)

In [41]:
wines[:,2]

array([0.  , 0.  , 0.04, ..., 0.13, 0.12, 0.47])

In [54]:
wines[1][5]=10
wines

slice_new=wines[:,9]
slice_new[:][:]=666
slice_new

array([666., 666., 666., ..., 666., 666., 666.])

In [75]:
print(wines.dtype)


wines1=wines.astype(int)
wines1

float64


array([[ 7,  0,  0, ...,  0,  9,  5],
       [ 7,  0,  0, ...,  0,  9,  5],
       [ 7,  0,  0, ...,  0,  9,  5],
       ...,
       [ 6,  0,  0, ...,  0, 11,  6],
       [ 5,  0,  0, ...,  0, 10,  5],
       [ 6,  0,  0, ...,  0, 11,  6]])

In [88]:
wines[:,11]+=10

print('column wise : ',sum(wines))
print('row wise : ',np.sum(wines,axis=1))
print('Sum of all : ',np.sum(arr))

column wise :  [1.33031000e+04 8.43985000e+02 4.33290000e+02 4.05955000e+03
 1.39859000e+02 2.53840000e+04 7.43020000e+04 1.59379794e+03
 5.29447000e+03 1.05238000e+03 3.26563500e+04 1.68912000e+05]
row wise :  [184.5438  233.0548  209.699   ... 210.48174 215.21547 202.49249]
Sum of all :  152084.78194


In [94]:
#qulity sum itself
wines[:,-1]+wines[:,-1]

wines[:,-2]*wines[:,-1]

array([47., 49., 49., ..., 66., 51., 66.])

In [122]:
print('greater than 5:',wines[np.where(wines[:,-1]>5)])

print('equal to 10:',wines[np.where(wines[:,-1]==10)])

print('Over 7',wines[np.where(wines[:,-1]>6)])

print(wines[np.where((wines[:,-1]>7) & (wines[:,-2]>10))])



greater than 5: [[11.2   0.28  0.56 ...  0.58  9.8   6.  ]
 [ 7.3   0.65  0.   ...  0.47 10.    7.  ]
 [ 7.8   0.58  0.02 ...  0.57  9.5   7.  ]
 ...
 [ 5.9   0.55  0.1  ...  0.76 11.2   6.  ]
 [ 6.3   0.51  0.13 ...  0.75 11.    6.  ]
 [ 6.    0.31  0.47 ...  0.66 11.    6.  ]]
equal to 10: []
Over 7 [[ 7.3   0.65  0.   ...  0.47 10.    7.  ]
 [ 7.8   0.58  0.02 ...  0.57  9.5   7.  ]
 [ 8.5   0.28  0.56 ...  0.75 10.5   7.  ]
 ...
 [ 7.4   0.36  0.3  ...  0.7  11.4   8.  ]
 [ 7.    0.56  0.17 ...  0.68 10.55  7.  ]
 [ 6.7   0.32  0.44 ...  0.8  11.6   7.  ]]
[[7.9000e+00 3.5000e-01 4.6000e-01 3.6000e+00 7.8000e-02 1.5000e+01
  3.7000e+01 9.9730e-01 3.3500e+00 8.6000e-01 1.2800e+01 8.0000e+00]
 [1.0300e+01 3.2000e-01 4.5000e-01 6.4000e+00 7.3000e-02 5.0000e+00
  1.3000e+01 9.9760e-01 3.2300e+00 8.2000e-01 1.2600e+01 8.0000e+00]
 [5.6000e+00 8.5000e-01 5.0000e-02 1.4000e+00 4.5000e-02 1.2000e+01
  8.8000e+01 9.9240e-01 3.5600e+00 8.2000e-01 1.2900e+01 8.0000e+00]
 [1.1300e+01 6.2000e-0

In [127]:
w1=wines.reshape(12, 1599)

print(w1)

w1.shape

[[7.40000e+00 7.00000e-01 0.00000e+00 ... 6.60000e+00 5.00000e-01
  1.00000e-02]
 [1.50000e+00 6.00000e-02 1.70000e+01 ... 3.30000e+00 9.60000e-02
  2.60000e+01]
 [6.10000e+01 1.00025e+00 3.60000e+00 ... 4.20000e+01 9.96300e-01
  3.10000e+00]
 ...
 [2.30000e+00 7.60000e-02 2.30000e+01 ... 1.70000e+00 7.50000e-02
  6.00000e+00]
 [2.50000e+01 9.95810e-01 3.09000e+00 ... 5.30000e+01 9.95800e-01
  3.41000e+00]
 [6.70000e-01 9.70000e+00 5.00000e+00 ... 6.60000e-01 1.10000e+01
  6.00000e+00]]


(12, 1599)